site_name: privates.py
site_url: https://privates.zintensity.dev
repo_url: https://github.com/ZeroIntensity/privates.py
repo_name: ZeroIntensity/privates.py

nav:
    - Home: index.md
    - Locking to Scope: scope_privates.md
    - Limiting Attributes: attributes.md
    - Reference: reference.md

theme:
    name: material
    palette:
        - media: "(prefers-color-scheme)"
          primary: blue
          accent: light blue
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          accent: light blue
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: light blue
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - content.tabs.link

    icon:
        repo: fontawesome/brands/github

markdown_extensions:
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
          alternate_style: true
plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
                  options:
                      show_root_heading: true
                      show_object_full_path: false
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      show_signature: true
                      seperate_signature: true
                      show_signature_annotations: true
                      signature_crossrefs: true
                      show_source: false
                      show_if_no_docstring: true
                      show_docstring_examples: false
